version: '3.7'

services:
  db:
    image: mysql:5.7
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress_password
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: wordpress_container
    restart: always
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress_password
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress_data:/var/www/html
      - ./php/formulario1/:/var/www/html/php_container/formulario1

  php:
    depends_on:
      - db
    image: php:7.4-apache
    container_name: php_container
    restart: always
    volumes:
      - wordpress_data:/var/www/html
      - ./php/formulario1/:/var/www/html/php_container/formulario1
    ports:
      - "8080:80"

volumes:
  db_data:
  wordpress_data:

